### ISSUE TITLE
Allow server to restart after stopping

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/pufferd#14]
A server should be allowed to auto-restart after being told to stop.

This should occur after a delay (if configured) and should be disabled.

This is independent of the auto-start feature, which only happens when pufferd starts.

**Comment by Plasticable** [comment]
Hey. How can i make my Sponge server restart after stopping or crashing? There is no auto start property in server `.json` file. 

PufferPanel version v1.2.4
