### ISSUE TITLE
Puffed crashes constantly for all services.

### ISSUE THREAD

**Issue by digitronics** [PufferPanel/pufferd#25]
Loaded: loaded (/etc/systemd/system/pufferd.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2017-03-09 18:59:26 EST; 1min 42s ago
Process: 9392 ExecStart=/srv/pufferd/pufferd --config /etc/pufferd/config.json (code=exited, status=2)
Main PID: 9392 (code=exited, status=2)

pufferd[9392]: [18:51:25] [ERROR] Error
pufferd[9392]: EOF
pufferd[9392]: [18:51:25] [ERROR] Error
pufferd[9392]: EOF
pufferd[9392]: [18:51:25] [ERROR] Error
pufferd[9392]: EOF
pufferd[9392]: panic: runtime error: slice bounds out of range
systemd[1]: pufferd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: pufferd.service: Unit entered failed state.
systemd[1]: pufferd.service: Failed with result 'exit-code'.

**Comment by digitronics** [comment]
all I could find on the error

**Comment by LordRalex** [comment]
What version of pufferd are you using?

cd /srv/pufferd
./pufferd --version

**Comment by digitronics** [comment]
Was using the latest, via the puffer website. Fresh install of Ubuntu 16.04 and Pufferd, the daemon was to unstable/lacking in features for me so moved over to Pterodactyl, sorry don't have the logs/daemon anymore.
