### ISSUE TITLE
Support reloading config.json upon SIGHUP

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/pufferd#26]
In order to make changes to config.json without having to restart pufferd entirely, pufferd should support being able to be reloaded, such as with systemctl reload pufferd.

**Comment by LordRalex** [comment]
This should also apply ssl changes, i.e when a letsencrypt cert is renewed, the web service uses the updated version

**Comment by LordRalex** [comment]
Command: pufferd --reload $MAINPID
