### ISSUE TITLE
SFTP Bug: Overwriting files results in appending them together

### ISSUE THREAD

**Issue by LJack2k** [PufferPanel/pufferd#33]
When uploading files instead of overwriting existing ones it appends them together.

![uploadfilesize](https://cloud.githubusercontent.com/assets/6696404/25675334/655b7e6e-303e-11e7-9428-4f056b916b6d.png)

Tested with WinSCP.

**Comment by puffrfish** [comment]
Fixed by 5fa65e354af1d8a9700289a4f00953655c1a86a4
