### ISSUE TITLE
Pufferd modifying server config file on startup

### ISSUE THREAD

**Issue by GoadingGoat** [PufferPanel/pufferd#37]
Pufferd modifies servers config files on startup. Revoking write access to the config file for pufferd solves the problem. Why is it modifying them in the first place? I can't find any code anywhere that suggests that pufferd writes to the config file. 
Upon creating a new server the config is written correctly.

The modification appears to be related to keys who have the same value but are defined at the top level, and nested as sub-keys. As well as the removal of empty lists.

Written config:
https://paste.ee/p/4q2Dh

template after restart
https://paste.ee/p/vXJoi

**Comment by puffrfish** [comment]
Thanks!
