### ISSUE TITLE
Use correct line separator in environment for the Operating System

### ISSUE THREAD

**Issue by GoadingGoat** [PufferPanel/pufferd#38]
Instead of using "/r' as the line separator when executing commands, the correct line separator should be specified for Linux and Windows.

Linux uses "\n",
Windows uses "\r\n"
While only some macs use "\r"

To go even further it would great if it was possible to detect the systems line seperator.

Most games seem to have support for using a single "\r", although not all do. One case is Sponge-Vanilla, which uses jline to detect the systems line.separator character.

**Comment by puffrfish** [comment]
Fixed with https://github.com/PufferPanel/pufferd/commit/79db5e44f848ec1394f053ae5210cecd6e89b73c

We will see how this performs on Windows.
