### ISSUE TITLE
Data files in central place

### ISSUE THREAD

**Issue by TakeMeNL** [PufferPanel/pufferd#40]
As of now all files are randomly over the system. Some in /srv some in /etc some in /var.  
Why can't we have 1 location on the system where everything lives.  
Config in /etc/ is fine btw

**Comment by LordRalex** [comment]
This approach was taken as it is how many applications work.

Nginx is a good example of a program that does this, as well as PHP.

Configs are stored in /etc, any runtime data is stored in /var.

http://www.thegeekstuff.com/2010/09/linux-file-system-structure/?utm_source=tuicool

While it's old, it is still accurate, and the approach taken by us by default.

You can easily change where files are located by changing the config and telling it a new location.

**Comment by TakeMeNL** [comment]
Thanks for the info about that.
