### ISSUE TITLE
node unreachable after upgrade

### ISSUE THREAD

**Issue by unixfox** [PufferPanel/pufferd#48]
I upgraded pufferpanel (pufferpanel and pufferd) from the version 1.1.2 to 1.1.4.

My node is now unreachable and pufferd keeps giving me TLS errors:
```
Sep 03 00:22:52 vps pufferd[7929]: [00:22:52] [INFO] Started SFTP Server on 0.0.0.0:5657
Sep 03 00:22:52 vps pufferd[7929]: [00:22:52] [INFO] Starting web access on 0.0.0.0:5656
Sep 03 00:22:57 vps pufferd[7929]: http: TLS handshake error from 51.254.48.211:51740: tls: first record does not look like a TLS handshake
Sep 03 00:22:57 vps pufferd[7929]: http: TLS handshake error from 51.254.48.211:51741: tls: first record does not look like a TLS handshake
```

If I try to manage a server I receive this error:
```
Unable to connect to web socket server, will attempt to use timed refresh
```

The SSL configuration is fine because it worked before upgrading and I resolved my main issue that I had in the past here: https://community.pufferpanel.com/topic/574/i-can-t-communicate-with-the-daemon-pufferd-when-using-https

What can I do to resolve this issue?

**Comment by unixfox** [comment]
Why closing my issue without replying to it?

**Comment by unixfox** [comment]
Why closing my issue without replying to it?

**Comment by LordRalex** [comment]
Because you need to update to 1.1.5

**Comment by unixfox** [comment]
I'm already using the 1.1.5 version of pufferd:
```
root@vps:/srv/pufferd# ./pufferd -version
[16:42:50] [INFO] No config passed, defaulting to /etc/pufferd/config.json
pufferd v1.1.5 (2017-08-26_03:15:30PM 79db5e44f848ec1394f053ae5210cecd6e89b73c)
```

**Comment by LordRalex** [comment]
Please join our community chat and ask your issue there. This does not seem like a bug directly on pufferd if anything, but it would be on the panel itself.
