### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by lucasdidur** [PufferPanel/pufferd#55]
Here the console log:

root@vps146591:~# pufferd -run
[10:24:46] [INFO] No config passed, defaulting to /etc/pufferd/config.json
[10:24:46] [INFO] pufferd v1.2.2 (781c0364881e9618c2f1fc72a5f608d0fd2e0ad0)
[10:24:46] [INFO] Logging set to INFO
[10:24:46] [INFO] Loaded server 043a5c0f-3a5f-4cfc-b650-52c396ac931e
[10:24:46] [INFO] Loaded server a194018c-0df6-4e49-8360-7f95c23b7007
[10:24:46] [INFO] Loaded server a255c275-10fb-4d60-bee1-87b856a1f263
[10:24:46] [INFO] Loaded server bd18bf55-243a-4d40-9610-1f3cf25113e3
[10:24:46] [INFO] Loaded server ffeba595-8bbf-4f11-913a-2ad0efd3179e
panic: path segment 'server' conflicts with existing wildcard ':id' in path '/server/server'

goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).addRoute(0xc42038c180, 0xc420386970, 0xe, 0xc4203816c0, 0x4, 0x4)
        /home/teamcity/buildAgent/work/e7f84bb11e91617a/src/github.com/gin-gonic/gin/tree.go:198 +0x60e
github.com/gin-gonic/gin.(*Engine).addRoute(0xc420382d80, 0xc1b130, 0x4, 0xc420386970, 0xe, 0xc4203816c0, 0x4, 0x4)
        /home/teamcity/buildAgent/work/e7f84bb11e91617a/src/github.com/gin-gonic/gin/gin.go:252 +0x1aa
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc420384640, 0xc1b130, 0x4, 0xc1d8f3, 0x7, 0xc420386940, 0x2, 0x2, 0xc420381601, 0xc420386940)
        /home/teamcity/buildAgent/work/e7f84bb11e91617a/src/github.com/gin-gonic/gin/routergroup.go:71 +0xe7
github.com/gin-gonic/gin.(*RouterGroup).POST(0xc420384640, 0xc1d8f3, 0x7, 0xc420386940, 0x2, 0x2, 0xf51de0, 0xc420384640)
        /home/teamcity/buildAgent/work/e7f84bb11e91617a/src/github.com/gin-gonic/gin/routergroup.go:94 +0x7c
github.com/pufferpanel/pufferd/routing/server.RegisterRoutes(0xc420382d80)
        /home/teamcity/buildAgent/work/e7f84bb11e91617a/src/github.com/pufferpanel/pufferd/routing/server/server.go:91 +0x10dc
github.com/pufferpanel/pufferd/routing.ConfigureWeb(0xc42037add0)
        /home/teamcity/buildAgent/work/e7f84bb11e91617a/src/github.com/pufferpanel/pufferd/routing/root.go:39 +0x12a
main.main()
        /home/teamcity/buildAgent/work/e7f84bb11e91617a/src/github.com/pufferpanel/pufferd/pufferd.go:202 +0xa50
root@vps146591:~#

**Comment by LordRalex** [comment]
https://github.com/PufferPanel/pufferd/commit/fda612fa5ed6af2d1b7904199a88d7568c018461

**Comment by LordRalex** [comment]
Please run the update via your package manager.

Ubuntu/Debian:
apt-get update
apt-get upgrade pufferd

CentOS:
yum update pufferd

**Comment by lucasdidur** [comment]
Thank you :D
