### ISSUE TITLE
Camel case of "logPath" does not correspond to all other lower case config variables

### ISSUE THREAD

**Issue by mapl** [PufferPanel/pufferd#59]
https://github.com/PufferPanel/pufferd/blob/32b8c6c5f4264c0ca8fa235d4abbb2ac56c06362/pufferd.go#L155

**Comment by LordRalex** [comment]
Camel casing is correct, all lowercase shouldn't really make sense. datafolder doesn't make sense to read, while dataFolder does. 

I would rather that be the change, than to make it logpath. We can update our config reader to handle reading it as whatever the code says, and lowercase if we don't find it.
