### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Blamo27** [PufferPanel/pufferd#66]
Puffer crash

● pufferd.service - pufferd daemon service
   Loaded: loaded (/lib/systemd/system/pufferd.service; enabled)
   Active: failed (Result: exit-code) since Sun 2018-09-02 14:16:44 CEST; 11min ago
  Process: 26310 ExecStop=/usr/sbin/pufferd --shutdown $MAINPID (code=exited, status=2)
 Main PID: 24961 (code=exited, status=2)

Sep 02 14:16:41 XXXX pufferd[26310]: -run
Sep 02 14:16:41 XXXX  pufferd[26310]: Runs the daemon
Sep 02 14:16:41 XXXX  pufferd[26310]: -shutdown int
Sep 02 14:16:41 XXXX  pufferd[26310]: PID to shut down
Sep 02 14:16:41 XXXX  pufferd[26310]: -token string
Sep 02 14:16:41 XXXX  pufferd[26310]: Authorization token
Sep 02 14:16:41 XXXX  pufferd[26310]: -version
Sep 02 14:16:41 XXXX  pufferd[26310]: Get the version
Sep 02 14:16:41 XXXX  systemd[1]: pufferd.service: control process exited, code=exited status=2
Sep 02 14:16:44 XXXX  systemd[1]: Unit pufferd.service entered failed state.

**Comment by Blamo27** [comment]
@LordRalex ??

**Comment by LordRalex** [comment]
Please use the [community forums](https://community.pufferpanel.com) for issues, questions, or help with installation or configuration of PufferPanel.
This issue tracker is only for confirmed bug reports. Please consider opening a thread on the community forums before opening an issue here.

**Comment by Blamo27** [comment]
@LordRalex Okey, i'll use it
