### ISSUE TITLE
How can I sent command to minecraft server via curl?

### ISSUE THREAD

**Issue by marrobHD** [PufferPanel/pufferd#69]
Hello,
How can I sent command to minecraft server via curl?

Thanks for help
~Marlon

**Comment by LordRalex** [comment]
Please use the [community forums](https://community.pufferpanel.com) for issues, questions, or help with installation or configuration of PufferPanel.
This issue tracker is only for confirmed bug reports. Please consider opening a thread on the community forums before opening an issue here.
