### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/pufferd#7]
A new environment needs to be created called docker, which handles the docker backend work.

**Comment by abates** [comment]
I'm interested in this feature.  Is there anything I can do to help?

**Comment by LordRalex** [comment]
Right now, we're at a standstill at implementing it.

We don't believe that the panel really can support what we need for it properly without making it look poor, so are looking at fixing that entire thing up first.

I am also starting to reconsider how the environments got set up, because each one has copied code, so I'd want to also consolidate what I can.

I had started the implementation, but halted on it because I could not find a good way to handle it on the UI with what docker needs (mainly, their networking at the time) so I've not pursued this farther.

What we are looking for in the end is that we just use docker for the container, and do not do any port-mapping like what Scales did, in which it said it was running on 25565 in the logs, but it was only because it's in a container.

We also have issues where if you need to alter the ports that are available for the container, there is no way to do that currently.

We are waiting for the panel-side of the "server edit" (there's actually 2 pages for it, one for users, and one for admins, as there is fields that users can edit, but some they can't), as that'd be needed for this implementation.
