### ISSUE TITLE
Download command not working with arrays

### ISSUE THREAD

**Issue by LiaraAlis** [PufferPanel/pufferd#72]
According to my pull request in https://github.com/PufferPanel/templates/pull/28, it seems that arrays in the `download` command are no longer working with an array of files.

Examples:
*not working*
```
{
    "type": "download",
    "files": [
        "https://s3-us-west-2.amazonaws.com/eco-releases/EcoServer_v${serverVersion}.zip"
    ]
}
```

*working*
```
{
    "type": "download",
    "files": "https://s3-us-west-2.amazonaws.com/eco-releases/EcoServer_v${serverVersion}.zip"
}
```

**Comment by LordRalex** [comment]
Do you have an error related to this to help?

**Comment by LordRalex** [comment]
Interestingly, the code path tells me that it's an issue with our lib, which that code didn't change in 2.x, but not sure why it works there. I'll put out a patch this weekend to fix it, since it shouldn't have happened.

Thanks for reporting it!
