### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by SharkblackFr** [PufferPanel/pufferd#75]
Hello,
I have an error 500 when load panel on web with indication: 
"Server Error
We're sorry! The server encountered an internal error and was unable to complete your request. Please try again later.

error 500 | 4. 11. 2020 19:58". 

 Thanks in advance for yout help

**Comment by LordRalex** [comment]
Please use our discord for assistance.

**Comment by SharkblackFr** [comment]
Juste please vive me a link because on your website is expired

**Comment by LordRalex** [comment]
Because you're using the wrong repo, and are not using our main website.

https://www.pufferpanel.com/
