### ISSUE TITLE
Add SFTP

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/pufferd#9]
SFTP should rely on validating user creds from PP

**Comment by nerdtron123** [comment]
@LordRalex Maybe you should make it that each puffer panel user has a SFTP access, and i dont know if you can set it up that they can only navigate inside the folders they have permission to navigate in etc. etc. else you should probably make it that the password displays on the page if possible, or you should make it that every user has a different ftp user or w/e or create your own FTP server for PufferD.
